version: '3'
services:
  db-erp:
    image: postgres
    container_name: db-erp
    restart: always
    tty: true
    environment:
      POSTGRES_DB: erp
      POSTGRES_USER: uaufi
      POSTGRES_PASSWORD: uaufi 
    volumes:
      - ../db/erp:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - uaufi_network


  api-erp:
    build: .
    container_name: api-erp
    entrypoint: dockerize -template ./.docker/.env-erp:.env -wait tcp://db-erp:5432 -timeout 180s ./.docker/docker-entrypoint.sh
    tty: true
    volumes:
      - ./:/usr/src/app/
    ports:
      - "3333:3333"
    links:
      - db-erp
    depends_on:
      - db-erp
    networks:
      - uaufi_network

      
networks:
  uaufi_network:
    driver: bridge
    name: uaufi_network